version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword00
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql/data
  php-apache:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./astro:/var/www/html
      - ./php:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
volumes:
  mssql-data: