services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    volumes:
      - final_project_mssql:/var/opt/mssql/data
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/php/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
volumes:
  final_project_mssql: